server:
  port: 8081
# Liquibase properties for H2 database and liquibase
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/stock_service_db
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml