apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microservice-gateway
  name: microservice-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microservice-gateway
    spec:
      containers:
      - image: app/gateway:v1
        name: gateway
        resources: {}
status: {}
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: microservice-gateway
  name: microservice-gateway
spec:
  ports:
  - name: 8080-8080
    nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: microservice-gateway
  type: NodePort
status:
  loadBalancer: {}
