pipeline {
    agent any
    tools {
            maven 'maven-3.9.2'
        }

    stages {
        stage ('SCM checkout') {
            steps {
                    echo 'Checking out git repository'
                    checkout scm
                    //git branch: 'main', url: 'https://github.com/myuser/myrepo.git'
                }
            }
        stage('Build') {
            steps {
                echo 'Building project'
                sh 'cd microservice-gateway && mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'run unit tests'
                sh 'cd microservice-gateway && mvn test'
            }
        }
    }
}