pipeline {
    agent any
    tools {
            maven 'maven-3.9.2'
        }

    stages {
        stage('Build') {
            steps {
                echo 'Building project'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'run unit tests'
                sh 'mvn test'
            }
        }
    }
}