server:
  port: 8081

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100

      circuitBreaker:
        requestVolumeThreshold: 2

# Setting Hystrix timeout for the chain in 300ms (we only have 1 service to call).
  # hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=300
  # This property sets the minimum number of requests in a rolling window that will trip the circuit.
# hystrix.command.default.circuitBreaker.requestVolumeThreshold=5